name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Triển khai khi có thay đổi trên nhánh chính

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build website
      run: npm run build  # Điều chỉnh nếu bạn có lệnh build khác

    - name: Deploy to Netlify
      run: |
        npm install -g netlify-cli
        netlify deploy --dir=build --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
